version: "3"

services:
  elasticsearch:
    image: elasticsearch:7.14.1
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - $PWD/data:/usr/share/elasticsearch/data
        #  - $PWD/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    image: kibana:7.14.1
    ports:
      - "5601:5601"
    links:
      - elasticsearch
