version: "3"

services:
  postgres:
    image: registry.gitlab.shiveh.com/upstream/postgis:11-extentions
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - $PWD/data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=aa.maesum@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=12345678
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "8080:80"
    volumes:
      - $PWD/data/pgadmin:/var/lib/pgadmin
    links:
      - "postgres"

volumes:
  postgres-data:
  pgadmin-data:
